export const SUPER_HEROES_STARTED : string = 'SUPER_HEROES_STARTED';
export const SUPER_HEROES_COMPLETED : string = 'SUPER_HEROES_COMPLETED';
export const SUPER_HEROES_FAILED : string = 'SUPER_HEROES_FAILED';

export const LIKE_SUPERHEROE : string = 'LIKE_SUPERHEROE';
export const UNLIKE_SUPERHEROE : string = 'UNLIKE_SUPERHEROE';